@authToken = Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbiIsInBlcm1pc3Npb25zIjpbeyJpZCI6MywibmFtZSI6IkRFTEVURV9QUk9EVUNUIn0seyJpZCI6NywibmFtZSI6IkdFVF9ISVNUT1JZX0RJU0NPVU5UIn0seyJpZCI6MiwibmFtZSI6IkFERF9QUk9EVUNUIn0seyJpZCI6NCwibmFtZSI6IlVQREFURV9QUk9EVUNUIn0seyJpZCI6OSwibmFtZSI6IkdFVF9JTlZPSUNFIn0seyJpZCI6MSwibmFtZSI6IkdFVF9QUk9EVUNUIn0seyJpZCI6NSwibmFtZSI6IkdFVF9ESVNDT1VOVCJ9LHsiaWQiOjgsIm5hbWUiOiJBRERfSU5WT0lDRSJ9LHsiaWQiOjEwLCJuYW1lIjoiR0VUX1JFUE9SVCJ9LHsiaWQiOjYsIm5hbWUiOiJBRERfRElTQ09VTlQifV0sImlhdCI6MTczNzA4NzAxOCwiZXhwIjoxNzM3MTA1MDE4fQ.pt_NPiqdzouAAYxuE6oF92h_oQAA1DHhk4ZXW7S_R86J1SjpO8LE8Jn9SGqc-u7zXltbmGi7ptCbPNIrYHS_5Q

###

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin123@"
}

###

POST http://localhost:8080/auth/sign-up
Content-Type: application/json

{
  "username": "anh",
  "password": "Admin123@",
  "name": "QA",
  "email": "anh@gmail.com"
}

###
GET http://localhost:8080/user/get-all

###

POST http://localhost:8080/products/add
Content-Type: application/json
Authorization: {{authToken}}

{
  "name": "milk",
  "price": 30000
}

###
GET http://localhost:8080/products/get-all
Authorization: {{authToken}}

###
POST http://localhost:8080/invoice/add
Content-Type: application/json
Authorization: {{authToken}}

{
  "customerEmail": "k@example.com",
  "customerName": "Customer Name",
  "invoiceDiscountId": 1,
  "items": [
    {
      "product": { "id": 1 },
      "quantity": 2,
      "productDiscountId": 1
    },
    {
      "product": { "id": 2 },
      "quantity": 3,
      "productDiscountId": 2
    }
  ]
}


###
GET http://localhost:8080/invoice

###
GET http://localhost:8080/report/revenue-by-month?startDate=2024-01-01&endDate=2025-01-20
Authorization: {{authToken}}

###
GET http://localhost:8080/report/revenue-by-quarter?startDate=2024-01-01&endDate=2025-01-05
Authorization: {{authToken}}

###
GET http://localhost:8080/report/revenue-by-year?startDate=2024-01-01&endDate=2025-01-05
Authorization: {{authToken}}

###
GET http://localhost:8080/discount-history/invoice/1
Authorization: {{authToken}}

###
GET  http://localhost:8080/discount
Authorization: {{authToken}}

###
POST http://localhost:8080/discount/add
Content-Type: application/json
Authorization: {{authToken}}

{
  "value": 10000,
  "type": "AMOUNT"
}

###
GET http://localhost:8080/permission

###

POST http://localhost:8080/permission/add
Content-Type: application/json

{
  "name": "ADD_PERMISSION"
}

###
POST http://localhost:8080/role/add
Content-Type: application/json

{
  "role": "Sale",
  "description": "",
  "permissions": [
    {"id": 2}
  ]
}

###
GET http://localhost:8080/role